<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PowerPlantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('power_plant')->insert(
            [
                [
                    'name' => 'PLTD MANDANGIN',
                    'code' => 'MDG',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 5,
                    'feeder_quantity' => 5,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTD GILI GENTING',
                    'code' => 'GLG',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTD GILI IYANG',
                    'code' => 'GLY',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTD SAPUDI',
                    'code' => 'SPD',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTD RAAS',
                    'code' => 'RAAS',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTD KANGEAN',
                    'code' => 'KGN',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTD SAPEKEN',
                    'code' => 'SPK',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTD GILI RAJA',
                    'code' => 'GLR',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTD SEPANJANG',
                    'code' => 'SPJ',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTD PAGURUNGAN KECIL',
                    'code' => 'PGRK',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTD PAGURUNGAN BESAR',
                    'code' => 'PGRB',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTD MASA LEMBU',
                    'code' => 'MSL',
                    'power_plant_type' => 'PLTD',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS TONDUK',
                    'code' => 'TDK',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS GOWA-GOWA',
                    'code' => 'GWA',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS SAOBI',
                    'code' => 'SBI',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS PAGURUNGAN KECIL',
                    'code' => 'P. KCL',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS SAKALA',
                    'code' => 'SKL',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS PALIAT',
                    'code' => 'PLT',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS SABUNTAN',
                    'code' => 'SBT',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS MASA KAMBING',
                    'code' => 'MSK',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS SAREDENG BESAR',
                    'code' => 'SAR. B',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS SAREDENG KECIL',
                    'code' => 'SAR. K',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS TALANGO AIR',
                    'code' => 'TLG. A',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PLTS TALANGO TENGAH',
                    'code' => 'TLG. T',
                    'power_plant_type' => 'PLTS',
                    'engine_quantity' => 0,
                    'feeder_quantity' => 0,
                    'estimated_usage_amount' => 0,
                    'dead_stock_amount' => 0,
                    'unit_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
