<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StaffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('staff')->insert(
            [
                [
                    'name' => 'PIC PLTD MANDANGIN',
                    'user_id' => 2,
                    'power_plant_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTD GILI GENTING',
                    'user_id' => 3,
                    'power_plant_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTD GILI IYANG',
                    'user_id' => 4,
                    'power_plant_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTD SAPUDI',
                    'user_id' => 5,
                    'power_plant_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTD RAAS',
                    'user_id' => 6,
                    'power_plant_id' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTD KANGEAN',
                    'user_id' => 7,
                    'power_plant_id' => 6,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTD SAPEKEN',
                    'user_id' => 8,
                    'power_plant_id' => 7,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTD GILI RAJA',
                    'user_id' => 9,
                    'power_plant_id' => 8,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTD SEPANJANG',
                    'user_id' => 10,
                    'power_plant_id' => 9,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTD PAGURUNGAN KECIL',
                    'user_id' => 11,
                    'power_plant_id' => 10,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTD PAGURUNGAN BESAR',
                    'user_id' => 12,
                    'power_plant_id' => 11,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTD MASA LEMBU',
                    'user_id' => 13,
                    'power_plant_id' => 12,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS TONDUK',
                    'user_id' => 14,
                    'power_plant_id' => 13,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS GOWA-GOWA',
                    'user_id' => 15,
                    'power_plant_id' => 14,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS SAOBI',
                    'user_id' => 16,
                    'power_plant_id' => 15,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS PAGURUNGAN KECIL',
                    'user_id' => 17,
                    'power_plant_id' => 16,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS SAKALA',
                    'user_id' => 18,
                    'power_plant_id' => 17,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS PALIAT',
                    'user_id' => 19,
                    'power_plant_id' => 18,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS SABUNTAN',
                    'user_id' => 20,
                    'power_plant_id' => 19,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS MASA KAMBING',
                    'user_id' => 21,
                    'power_plant_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS SAREDENG BESAR',
                    'user_id' => 22,
                    'power_plant_id' => 21,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS SAREDENG KECIL',
                    'user_id' => 23,
                    'power_plant_id' => 22,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS TALANGO AIR',
                    'user_id' => 24,
                    'power_plant_id' => 23,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIC PLTS TALANGO TENGAH',
                    'user_id' => 25,
                    'power_plant_id' => 24,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD MANDANGIN',
                    'user_id' => 26,
                    'power_plant_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD GILI GENTING',
                    'user_id' => 27,
                    'power_plant_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD GILI IYANG',
                    'user_id' => 28,
                    'power_plant_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD SAPUDI',
                    'user_id' => 29,
                    'power_plant_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD RAAS',
                    'user_id' => 30,
                    'power_plant_id' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD KANGEAN',
                    'user_id' => 31,
                    'power_plant_id' => 6,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD SAPEKEN',
                    'user_id' => 32,
                    'power_plant_id' => 7,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD GILI RAJA',
                    'user_id' => 33,
                    'power_plant_id' => 8,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD SEPANJANG',
                    'user_id' => 34,
                    'power_plant_id' => 9,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD PAGURUNGAN KECIL',
                    'user_id' => 35,
                    'power_plant_id' => 10,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD PAGURUNGAN BESAR',
                    'user_id' => 36,
                    'power_plant_id' => 11,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTD MASA LEMBU',
                    'user_id' => 37,
                    'power_plant_id' => 12,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS TONDUK',
                    'user_id' => 38,
                    'power_plant_id' => 13,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS GOWA-GOWA',
                    'user_id' => 39,
                    'power_plant_id' => 14,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS SAOBI',
                    'user_id' => 40,
                    'power_plant_id' => 15,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS PAGURUNGAN KECIL',
                    'user_id' => 41,
                    'power_plant_id' => 16,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS SAKALA',
                    'user_id' => 42,
                    'power_plant_id' => 17,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS PALIAT',
                    'user_id' => 43,
                    'power_plant_id' => 18,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS SABUNTAN',
                    'user_id' => 44,
                    'power_plant_id' => 19,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS MASA KAMBING',
                    'user_id' => 45,
                    'power_plant_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS SAREDENG BESAR',
                    'user_id' => 46,
                    'power_plant_id' => 21,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS SAREDENG KECIL',
                    'user_id' => 47,
                    'power_plant_id' => 22,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS TALANGO AIR',
                    'user_id' => 48,
                    'power_plant_id' => 23,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'OPERATOR PLTS TALANGO TENGAH',
                    'user_id' => 49,
                    'power_plant_id' => 24,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
